# Generated by Django 3.1 on 2020-10-25 12:19

from django.db import migrations, models
import first_app.choices


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_profile_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loyality',
            field=models.CharField(choices=[('PLATINUM_CARD', 'Platinum'), ('GOLDEN_CARD', 'Gold'), ('SILVER_CARD', 'Silver')], default=first_app.choices.LoyalityPrograms['SILVER_CARD'], max_length=13),
        ),
    ]
